### PR TITLE
Support hid_get_input_report

### LINKED ISSUE #45: Missing `hid_get_input_report()`
The package seems to be missing one of the `hidapi` functions. The library offers two 'get_report'-functions `hid_get_feature_report()` and `hid_get_input_report()`(see below). The former works nicely, while the latter is not implemented.
Is this on purpose because`hid_get_input_report()` is not working fully on all platforms yet? 

```c
/** @brief Get a feature report from a HID device.
			Set the first byte of @p data[] to the Report ID of the
			report to be read.  Make sure to allow space for this
			extra byte in @p data[]. Upon return, the first byte will
			still contain the Report ID, and the report data will
			start in data[1].
			This function sets the return value of hid_error().
			@ingroup API
			@param dev A device handle returned from hid_open().
			@param data A buffer to put the read data into, including
				the Report ID. Set the first byte of @p data[] to the
				Report ID of the report to be read, or set it to zero
				if your device does not use numbered reports.
			@param length The number of bytes to read, including an
				extra byte for the report ID. The buffer can be longer
				than the actual report.
			@returns
				This function returns the number of bytes read plus
				one for the report ID (which is still in the first
				byte), or -1 on error.
		*/
		int HID_API_EXPORT HID_API_CALL hid_get_feature_report(hid_device *dev, unsigned char *data, size_t length);

		/** @brief Get a input report from a HID device.
			Set the first byte of @p data[] to the Report ID of the
			report to be read. Make sure to allow space for this
			extra byte in @p data[]. Upon return, the first byte will
			still contain the Report ID, and the report data will
			start in data[1].
			@ingroup API
			@param device A device handle returned from hid_open().
			@param data A buffer to put the read data into, including
				the Report ID. Set the first byte of @p data[] to the
				Report ID of the report to be read, or set it to zero
				if your device does not use numbered reports.
			@param length The number of bytes to read, including an
				extra byte for the report ID. The buffer can be longer
				than the actual report.
			@returns
				This function returns the number of bytes read plus
				one for the report ID (which is still in the first
				byte), or -1 on error.
		*/
		int HID_API_EXPORT HID_API_CALL hid_get_input_report(hid_device *dev, unsigned char *data, size_t length);
```
from: https://github.com/libusb/hidapi/blob/master/hidapi/hidapi.h

### PR DESCRIPTION
**Pull request by geneccx**
Closes #45

### CODE REVIEW

**Comment by fauxpark** [comment]
This causes issues for some distros - for example the latest Linux Mint versions are still based on Ubuntu Focal, which only have libhidapi-hidraw0 0.9.0:
https://packages.ubuntu.com/search?keywords=libhidapi-hidraw0&searchon=names&suite=all&section=all

So trying to use this library results in `AttributeError: /lib/x86_64-linux-gnu/libhidapi-hidraw0.so: undefined symbol: hid_get_input_report`.

**Comment by apmorton** [comment]
Does this exception get thrown when importing the library or when calling hid_get_input_report?

**Comment by fauxpark** [comment]
On import. Here's the traceback that was reported:
image

**Comment by apmorton** [comment]
As a workaround you can try downloading this package from 1.0.5 to 1.0.4

I will address this in a future release.

**Pull request merged**
