### PR TITLE
Add support for 'bus_type' filed

### PR DESCRIPTION
**Pull request by ndreys**
Starting with version 0.13, struct hid_device_info has an extra data field that indicates the type of the underlying HID transport used by the device. Add plumbing necessary to expose that via DeviceInfo class. We also introduce BusType enum that mirrors its C-equivalent "hid_bus_type".

### CODE REVIEW

**Comment by apmorton** [comment]
`hid_version` is itself fairly new in the grand scheme of hidapi - can you make sure we continue to support older versions of hidapi that don't have hid_version?

https://github.com/libusb/hidapi/commit/8f72236099290345928e646d2f2c48f0187ac4af

**Comment by ndreys** [comment]
Yea, good point, I'll add code to handle that

**Comment by ndreys** [comment]
Added

**Review by apmorton — APPROVED** [review]

**Comment by apmorton** [comment]
Thanks!

1.0.6 has been released on pypi

**Pull request merged**
