### PR TITLE
support 64bit

### PR DESCRIPTION
**Pull request by HAL9HARUKU**
Avoid crash when using 64bit python

### CODE REVIEW

**Comment by apmorton** [comment]
Chances are good the return type you added is also correct for 32bit - do you mind trying without the 64bit condition on a 32bit python?

**Comment by HAL9HARUKU** [comment]
Thanks!
Worked without the 64bit condition on a 32bit python.

**Comment by apmorton** [comment]
can you please test the code on master? I committed the changes suggested in #16, which should be equivalent to your PR, except for all hidapi exports

**Comment by HAL9HARUKU** [comment]
I tested the code on master, it worked well.
Thanks!

**Pull request closed without merging**
